o noua tema frumoasa
cs-utcn-group-3/1-cp pull request #117
Opened 2019-11-05 18:09 UTC by zaraantonia

2019-11-06 06:00 UTC, Alex-Cosma requested changes

2019-11-06 06:00 UTC, Alex-Cosma commented on Zara Antonia-Maria/L7/3.4/main.c
> +    for(i=0;i<length1;i++)
Curly brackets

2019-11-06 06:00 UTC, Alex-Cosma commented on Zara Antonia-Maria/L7/3.8/main.c
> +    for(i=0;i<=order2;i++)
Ugh, acolade!!
Codul e scris bine dar arată urât

2019-11-06 06:00 UTC, Alex-Cosma commented on Zara Antonia-Maria/L7/3.8/main.c
> +int main()
E prea lungă funcția main, trebuie spartă în mai multe funcții

2019-11-06 06:00 UTC, Alex-Cosma commented on Zara Antonia-Maria/L7/3.9/main.c
> +///se blocheaza dupa citirea matricei si mor
Nu muri.

Unde se blochează mai exact?

2019-11-06 06:01 UTC, Alex-Cosma requested changes

2019-11-06 06:01 UTC, Alex-Cosma commented on Zara Antonia-Maria/L7/3.7/main.c
> +        for(i=0;i<=order;i++)coefficients[i]=0;
Corect. Dar și mai bine ar fi să ai acolade

2019-11-06 06:01 UTC, Alex-Cosma commented on Zara Antonia-Maria/L7/3.7/main.c
> +    else
Și ă muți asta într-o funcție

2019-11-10 22:09 UTC, Alex-Cosma reviewed
Nu ești singura cu probleme la 3.6 - poate ar fi fain să o discutăm la laborator (nu țin minte nici măcar eu să o fi făcut vreodată, dar o putem gândi împreună)

2019-11-10 22:09 UTC, Alex-Cosma commented on Zara Antonia-Maria/L8/3.2-3.6/main.c
> +    char string[1001]; ///nu pot declara cu pointer pentru ca nu am de unde sa stiu lungimea sirului
Păi tocmai de-asta nu trebuie să îl declari static.

Tu mai jos calculezi `nrDigits`, nu?

=> după ce îl știi, dacă tu ai declara la început 
```
char * string;
```
de ce nu ai putea apoi să scrii
```
string = (int*) malloc(sizeof(char)*nrDigits);
```
?

2019-11-10 22:09 UTC, Alex-Cosma commented
Mă bucur că lucrezi și postezi lucruri, keep up the good work

2019-11-10 22:09 UTC, merged

2019-11-12 14:07 UTC, zaraantonia commented on Zara Antonia-Maria/L8/3.2-3.6/main.c
> +    char string[1001]; ///nu pot declara cu pointer pentru ca nu am de unde sa stiu lungimea sirului
Ah. Ok, nu m-am gandit, aveam impresia ca pot face alocarea doar fix dupa declarare si ca nu mai pot sa scriu instructiuni intre ele, dar acum am realizat ca atata timp cat nu folosesc fix string-ul ala
e ok, multumeeesc.

2019-11-13 13:28 UTC, Alex-Cosma commented on Zara Antonia-Maria/L8/3.2-3.6/main.c
> +    char string[1001]; ///nu pot declara cu pointer pentru ca nu am de unde sa stiu lungimea sirului
N-ai pentru ceee