Nu stiu de ce nu imi functioneaza afisarea.
cs-utcn-group-3/1-cp pull request #147
Opened 2019-11-22 10:12 UTC by cristicrisan07

2019-11-24 06:57 UTC, Alex-Cosma commented
Ce anume nu funcționează?

2019-11-24 16:31 UTC, cristicrisan07 commented
Cand ajunge sa execute functia de  afisare , si executa printf, nu se mai intampla nimic

2019-11-24 19:53 UTC, Alex-Cosma commented
Ai debuguit?

2019-11-24 20:22 UTC, cristicrisan07 commented
Am pus in acel for din funcția de afisare un printf("da") inainte de printul mare, si am văzut ca se blochează la cel mare

2019-12-25 22:11 UTC, Alex-Cosma requested changes

2019-12-25 22:11 UTC, Alex-Cosma commented on Crisan Cristian Alexandru/010 3.3/student.c
> +        scanf("%s",&students[i].name);
Aici e problema. Grijă mare!
`students[i].name` e deja un `char *` (adică un pointer)
nu are niciun sens să mai pui `&` înainte!
Probabil știai asta dar ai pus-o din instinct/neatenție.

2019-12-25 22:11 UTC, Alex-Cosma commented on Crisan Cristian Alexandru/010 3.3/student.c
> +        scanf("%s",&students[i].name);
Același lucru și mai jos, la adresă

2019-12-25 22:11 UTC, Alex-Cosma commented on Crisan Cristian Alexandru/Casualwood/rws.c
> +                strcpy(actors[*nrOfDactors].name,info);
Problema ta nu e aici

2019-12-25 22:11 UTC, Alex-Cosma commented on Crisan Cristian Alexandru/Casualwood/rws.c
> +        strcpy(movies[*nrOfDMovies].name,info);
Problema ta e de fapt, aici - dacă ai fi mers cu debuggerul, ai fi văzut că de fapt aici crapă, nu mai jos.
Motivul e simplu - tu ai un array de filme, `movies`. Fiecare `movie` are un `char * name` pe lângă alte cele. Ideea e că, degeaba în funcția main ai declarat tu:
`movie *movies=(movie*)malloc(sizeof(movie)*30);`
că tu ai alocat spațiu doar pentru 30 de pointeri către 30 de obiecte de tipul `movie`, pe când, fiecare dintre aceste 30 de obiecte conțin un pointer către un `char * name` <-- *ȘI ĂSTA* trebuie alocat!

Uită-te la exemplele pe care le-am făcut eu. De fiecare dată când aloc o structură care mai are un șir de .. ceva, orice, aloc și acel șir! (de obicei am denumit funcțiile de alocare `initialize ... `

2019-12-28 12:58 UTC, Alex-Cosma commented
Mă bucur că ai rezolvat

2019-12-28 12:58 UTC, merged