Minim si maxim
cs-utcn-group-3/1-cp pull request #65
Opened 2019-10-16 08:16 UTC by TudorChindea

2019-10-16 10:10 UTC, Alex-Cosma requested changes

2019-10-16 10:10 UTC, Alex-Cosma commented on Chindea Tudor Eugen/Lab3 CP/main.c
> +        if(i==0)
You should initialize `mini`,`maxi`,`pozmin` and `pozmax` at the beginning so you won't need to use this if here
Also, why are `pozmin` and `pozmax` vectors? it doesn't make sense

2019-10-16 10:10 UTC, Alex-Cosma commented on Chindea Tudor Eugen/Lab3 CP/main.c
> +            else if(sequence[i]==maxi)
Well, if this is true, then the maximum number is still `maxi`, and I think you can simply leave it as it is, no need to do anything more about it

2019-10-16 10:10 UTC, Alex-Cosma commented on Chindea Tudor Eugen/Lab3 CP/main.c
> +            else if(sequence[i]==mini)
Same for minimum, just leave as is

2019-10-16 10:12 UTC, Alex-Cosma requested changes

2019-10-16 10:12 UTC, Alex-Cosma commented on Chindea Tudor Eugen/Lab3-pb 3.4/main.c
> +int main()
Goodie

2019-10-18 18:29 UTC, TudorChindea commented
pozmin and pozmax are vectors because the problem requires to print the positions.. Not the first position where the maximum and minimum walues appear

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 16, 2019 at 13:12, Cosma Alex<notifications@github.com> wrote:   
@Alex-Cosma requested changes on this pull request.

In Chindea Tudor Eugen/Lab3-pb 3.4/main.c:
> @@ -0,0 +1,27 @@
+#include <stdio.h>
+#include <stdlib.h>
+int nrprim(int x)
+{
+    int diviz=2;
+    while(diviz*diviz<=x)
+    {
+        if(x%diviz==0)
+            return 0;
+        diviz++;
+    }
+    return 1;
+}
+int main()

Goodie

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-19 09:19 UTC, Alex-Cosma commented on Chindea Tudor Eugen/Lab3 CP/main.c
> +        if(i==0)
Fair enough, you are right on that

2019-10-19 09:19 UTC, merged